[View in Colaboratory](https://colab.research.google.com/github/aishasonkar/ML_ON12/blob/master/13th_assignment.ipynb)

In [0]:
import pandas as pd
import numpy as np
from sklearn import datasets

### a) Import iris dataset from sklearn.###


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
dataset=datasets.load_iris()

In [72]:
data

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

### b) Split the dataset into training and testing sets using train_test_split()  ###


In [0]:
from sklearn.naive_bayes import GaussianNB

In [0]:
X=dataset.data

In [75]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
Y=dataset.target

### c) Use GaussianNB and print the following: ###


i. Confusion matrix
ii. Classification report




In [0]:
model=GaussianNB()

In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=2)

In [79]:
model.fit(X_train,Y_train)

GaussianNB(priors=None)

In [80]:
print(model)

GaussianNB(priors=None)


In [0]:
pred=model.predict(X_test)

In [0]:
from sklearn import metrics

In [83]:
 print(metrics.accuracy_score(Y_test,pred))

0.9777777777777777


In [84]:
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        17
          1       1.00      0.93      0.97        15
          2       0.93      1.00      0.96        13

avg / total       0.98      0.98      0.98        45



In [85]:
print(metrics.confusion_matrix(Y_test,pred))

[[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]


###  d) Use MultinomialNB and print the following: ###

> 
i. Confusion matrix
ii. Classification report




In [0]:
from sklearn.naive_bayes import MultinomialNB

In [0]:
model1=MultinomialNB()

In [90]:

model1.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
pred=model1.predict(X_test)

In [92]:
 print(metrics.accuracy_score(Y_test,pred))

0.9111111111111111


In [93]:
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        17
          1       1.00      0.73      0.85        15
          2       0.76      1.00      0.87        13

avg / total       0.93      0.91      0.91        45



In [94]:
print(metrics.confusion_matrix(Y_test,pred))

[[17  0  0]
 [ 0 11  4]
 [ 0  0 13]]


In [64]:
Y_train.size

105