[View in Colaboratory](https://colab.research.google.com/github/aishasonkar/ML_ON12/blob/master/14th_assignment.ipynb)

In [10]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits


In [11]:
from sklearn.model_selection import train_test_split

### import dataset ###

In [12]:
digit=load_digits()

In [13]:
X=digit.data

In [14]:
Y=digit.target

### Q.2- Split the dataset into training and testing sets using train_test_split() ###

In [15]:


from sklearn.cross_validation import train_test_split


/usr/local/lib/python3.6/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=3)

### Q.3- Use SVM with kernels  ###

> 
a. Linear
b. Poly
c. Gaussian
d. Sigmoid
For every kernel, print the following: 
a. Confusion Matrix
b. Classification Report




In [17]:
from sklearn.svm import SVC

In [18]:
linea = SVC(kernel='linear')


In [22]:
from sklearn import metrics

In [19]:
linea.fit(X_train,Y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
pred=linea.predict(X_test)

In [23]:
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        64
          1       0.87      0.98      0.92        56
          2       1.00      1.00      1.00        56
          3       1.00      0.98      0.99        56
          4       0.98      0.93      0.96        61
          5       0.98      0.96      0.97        49
          6       1.00      0.98      0.99        42
          7       0.95      0.96      0.96        57
          8       0.96      0.88      0.92        52
          9       0.92      0.96      0.94        47

avg / total       0.97      0.96      0.96       540



In [24]:
print(metrics.confusion_matrix(Y_test,pred))

[[64  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  1  0]
 [ 0  0 56  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  1  0]
 [ 0  3  0  0 57  0  0  1  0  0]
 [ 0  0  0  0  0 47  0  0  0  2]
 [ 0  1  0  0  0  0 41  0  0  0]
 [ 0  0  0  0  1  0  0 55  0  1]
 [ 0  4  0  0  0  0  0  1 46  1]
 [ 0  0  0  0  0  1  0  1  0 45]]


In [8]:
polynomial=SVC(kernel='poly',degree=7)

In [25]:
polynomial.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=7, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
pred=polynomial.predict(X_test)

In [54]:
from sklearn import metrics

In [55]:
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        64
          1       0.95      0.93      0.94        56
          2       1.00      0.98      0.99        56
          3       0.98      0.98      0.98        56
          4       0.97      0.98      0.98        61
          5       0.98      0.96      0.97        49
          6       1.00      0.95      0.98        42
          7       0.97      0.98      0.97        57
          8       0.92      0.92      0.92        52
          9       0.94      0.98      0.96        47

avg / total       0.97      0.97      0.97       540



In [56]:
print(metrics.confusion_matrix(Y_test,pred))

[[64  0  0  0  0  0  0  0  0  0]
 [ 1 52  0  0  0  1  0  0  1  1]
 [ 0  0 55  0  0  0  0  1  0  0]
 [ 0  0  0 55  0  0  0  0  1  0]
 [ 0  0  0  0 60  0  0  1  0  0]
 [ 0  0  0  0  1 47  0  0  0  1]
 [ 0  1  0  0  0  0 40  0  1  0]
 [ 0  0  0  0  0  0  0 56  1  0]
 [ 0  2  0  1  0  0  0  0 48  1]
 [ 0  0  0  0  1  0  0  0  0 46]]


In [34]:

gaussian=SVC(kernel='rbf')

In [35]:
gaussian.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [36]:
pred1=gaussian.predict(X_test)

In [37]:
print(metrics.classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      0.39      0.56        64
          1       1.00      0.30      0.47        56
          2       1.00      0.29      0.44        56
          3       1.00      0.36      0.53        56
          4       1.00      0.18      0.31        61
          5       0.13      1.00      0.24        49
          6       1.00      0.69      0.82        42
          7       1.00      0.30      0.46        57
          8       1.00      0.02      0.04        52
          9       1.00      0.77      0.87        47

avg / total       0.92      0.41      0.46       540



In [38]:
print(metrics.confusion_matrix(Y_test,pred))

[[64  0  0  0  0  0  0  0  0  0]
 [ 1 52  0  0  0  1  0  0  1  1]
 [ 0  0 55  0  0  0  0  1  0  0]
 [ 0  0  0 55  0  0  0  0  1  0]
 [ 0  0  0  0 60  0  0  1  0  0]
 [ 0  0  0  0  1 47  0  0  0  1]
 [ 0  1  0  0  0  0 40  0  1  0]
 [ 0  0  0  0  0  0  0 56  1  0]
 [ 0  2  0  1  0  0  0  0 48  1]
 [ 0  0  0  0  1  0  0  0  0 46]]


In [39]:
sigmo=SVC(kernel='sigmoid')

In [40]:
sigmo.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [41]:
pred2=gaussian.predict(X_test)

In [42]:
print(metrics.classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      0.39      0.56        64
          1       1.00      0.30      0.47        56
          2       1.00      0.29      0.44        56
          3       1.00      0.36      0.53        56
          4       1.00      0.18      0.31        61
          5       0.13      1.00      0.24        49
          6       1.00      0.69      0.82        42
          7       1.00      0.30      0.46        57
          8       1.00      0.02      0.04        52
          9       1.00      0.77      0.87        47

avg / total       0.92      0.41      0.46       540



In [43]:
print(metrics.confusion_matrix(Y_test,pred2))

[[25  0  0  0  0 39  0  0  0  0]
 [ 0 17  0  0  0 39  0  0  0  0]
 [ 0  0 16  0  0 40  0  0  0  0]
 [ 0  0  0 20  0 36  0  0  0  0]
 [ 0  0  0  0 11 50  0  0  0  0]
 [ 0  0  0  0  0 49  0  0  0  0]
 [ 0  0  0  0  0 13 29  0  0  0]
 [ 0  0  0  0  0 40  0 17  0  0]
 [ 0  0  0  0  0 51  0  0  1  0]
 [ 0  0  0  0  0 11  0  0  0 36]]
