[View in Colaboratory](https://colab.research.google.com/github/aishasonkar/ML_ON12/blob/master/2nd_assignment.ipynb)

In [0]:
import numpy as np


In [0]:
Q1. Create a numpy array with 10 elements of shape (10,1) using np.random and find out the mean of using numpy function

In [0]:
e=np.random.rand(1,20)

In [48]:
e

array([[0.56729616, 0.89830581, 0.99752024, 0.50462508, 0.16899439,
        0.31446028, 0.54471198, 0.83992727, 0.59514986, 0.10840446,
        0.46317873, 0.26526906, 0.40258449, 0.08457925, 0.27902166,
        0.96011041, 0.78527861, 0.24766739, 0.06583324, 0.76486576]])

In [0]:
a=e.reshape(20,1)

In [53]:
a

array([[0.56729616],
       [0.89830581],
       [0.99752024],
       [0.50462508],
       [0.16899439],
       [0.31446028],
       [0.54471198],
       [0.83992727],
       [0.59514986],
       [0.10840446],
       [0.46317873],
       [0.26526906],
       [0.40258449],
       [0.08457925],
       [0.27902166],
       [0.96011041],
       [0.78527861],
       [0.24766739],
       [0.06583324],
       [0.76486576]])

In [54]:
np.mean(a)

0.49288920627333255

**bold text**

Q2. Create a numpy array with 20 elements of the shape(20,1) using np.random() find the variance and standard deviation of array.

---


2.   List item



In [0]:
b=np.random.rand(1,20 )

In [0]:
c=np.array(b)

**bold text**

In [38]:
c

array([[0.00618128, 0.15303732, 0.29161926, 0.34848451, 0.8436278 ,
        0.20446286, 0.3461495 , 0.14933658, 0.14876291, 0.961283  ,
        0.81725403, 0.72723261, 0.54079831, 0.03570732, 0.26341632,
        0.91696923, 0.24116341, 0.85677793, 0.84647323, 0.20835334]])

In [0]:
d=c.reshape(20,1)

In [44]:
np.var(d)

0.10289220235712981

In [45]:
np.std(d)

0.3207681442368145

Q3.  - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [0]:
d=np.random.rand(10,20)

In [56]:
d

array([[0.35493515, 0.82659189, 0.64636216, 0.08726986, 0.61718568,
        0.59551939, 0.51980834, 0.88945408, 0.28604931, 0.7313383 ,
        0.69262755, 0.06512534, 0.06381578, 0.39922385, 0.29227455,
        0.86508464, 0.8008533 , 0.24668626, 0.65904286, 0.24682919],
       [0.0282066 , 0.237882  , 0.22851927, 0.08326203, 0.25113721,
        0.04669866, 0.98579433, 0.09547079, 0.34605037, 0.9803015 ,
        0.63110289, 0.69894175, 0.92570162, 0.31178048, 0.8314072 ,
        0.00177262, 0.67525113, 0.41648344, 0.44835707, 0.61854926],
       [0.4893207 , 0.89043029, 0.96254313, 0.44966948, 0.67374166,
        0.26918053, 0.31440342, 0.11438857, 0.5805699 , 0.33063957,
        0.61980054, 0.18244407, 0.54781373, 0.92786131, 0.55903495,
        0.52294442, 0.86070919, 0.76961189, 0.51050062, 0.29153798],
       [0.40772117, 0.11767587, 0.99794413, 0.65374956, 0.19888445,
        0.14086032, 0.62788999, 0.6688508 , 0.41377156, 0.27769072,
        0.30793237, 0.45919987, 0.04422656, 0

In [0]:
e=np.random.rand(20,25)

In [60]:
e

array([[0.27478919, 0.34792668, 0.37339854, 0.77930554, 0.65315226,
        0.55351779, 0.15326383, 0.06372073, 0.38736681, 0.32890088,
        0.22863312, 0.69246454, 0.6030391 , 0.41578382, 0.81603119,
        0.07518975, 0.53785371, 0.60501408, 0.63034456, 0.38594598,
        0.58992438, 0.94084184, 0.8886181 , 0.08410593, 0.19797602],
       [0.86267398, 0.13317402, 0.57024606, 0.83318495, 0.71887229,
        0.47155142, 0.71036004, 0.72593297, 0.34584626, 0.69767409,
        0.31081886, 0.13626929, 0.70940434, 0.86421965, 0.0906401 ,
        0.0589305 , 0.21760417, 0.08899798, 0.82268604, 0.85845546,
        0.5619942 , 0.84331717, 0.01431277, 0.30449859, 0.52703553],
       [0.05750708, 0.86143669, 0.39528899, 0.79488442, 0.11603092,
        0.54077793, 0.24169655, 0.6907369 , 0.29339709, 0.27662511,
        0.80749376, 0.64653832, 0.61783731, 0.67219064, 0.84722591,
        0.24092172, 0.28046346, 0.07353918, 0.01931528, 0.80222022,
        0.7108661 , 0.99238783, 0.81546901, 0.

In [0]:
g=np.dot(d,e)

In [62]:
g

array([[3.74009862, 4.66438528, 5.44966306, 3.98747531, 4.68841829,
        5.20135303, 4.56023984, 5.08684103, 4.36660475, 4.76568631,
        5.28432761, 4.47700689, 5.97409005, 5.04978087, 5.93122142,
        3.57745071, 3.41100874, 3.69851588, 4.54164309, 6.35173683,
        5.35693227, 4.7678742 , 5.13362133, 3.84803975, 5.66937409],
       [4.11706863, 3.56220336, 4.74091647, 3.85284856, 4.45865204,
        4.80113048, 3.54598223, 5.62178698, 3.58592162, 4.82441495,
        4.47659896, 3.77044802, 4.80677085, 4.4212805 , 5.74298552,
        3.89759736, 2.69780598, 4.09821249, 4.11524033, 5.66232403,
        4.01379006, 4.8448144 , 3.95097966, 4.17115675, 5.12762032],
       [4.37992086, 5.43671925, 6.16282612, 4.84691821, 5.32695643,
        5.75752352, 5.32382569, 6.0434472 , 4.6270535 , 5.82429652,
        5.96301568, 5.25630162, 5.86273688, 5.59998761, 6.22863825,
        4.37073404, 3.3989953 , 4.23187461, 5.31637181, 6.85041323,
        5.73081188, 6.55480517, 5.15552261, 4.

In [63]:
g.shape

(10, 25)

Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 


In [0]:
a=np.random.rand(1,10)

In [5]:
a

array([[0.71887034, 0.93198907, 0.29114232, 0.62686897, 0.96886633,
        0.12880614, 0.50497684, 0.94358846, 0.04116121, 0.18372065]])

In [0]:
b=a.reshape(10,1)

In [8]:
b

array([[0.71887034],
       [0.93198907],
       [0.29114232],
       [0.62686897],
       [0.96886633],
       [0.12880614],
       [0.50497684],
       [0.94358846],
       [0.04116121],
       [0.18372065]])

In [0]:
c=1/(1+np.exp(-b))

In [13]:
c

array([[0.67235821],
       [0.71747865],
       [0.57227577],
       [0.65177917],
       [0.72489348],
       [0.53215709],
       [0.62362819],
       [0.71982394],
       [0.51028885],
       [0.54580141]])